# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('connect_id', models.CharField(max_length=40, verbose_name='Stripe Connect Account Id')),
                ('bank_account_id', models.CharField(max_length=40, verbose_name='Stripe Bank Account (Source) Id')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('bank_account_number', models.CharField(max_length=4, verbose_name='Last 4 digits of account number')),
                ('bank_routing_number', models.CharField(max_length=50, verbose_name='Bank Rounting Number')),
                ('bank_account_status', models.CharField(max_length=30, verbose_name='Stripe Bank Account Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
