# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='dob',
            field=models.DateField(default=datetime.datetime(2017, 8, 4, 14, 4, 47, 428576), verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
