# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_chef_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='legal_entity_type',
            field=models.CharField(choices=[('individual', 'individual'), ('company', 'company')], default='individual', max_length=10),
            preserve_default=False,
        ),
    ]
