# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0004_auto_20170804_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='address_line_1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chef',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='ssn_last_4',
            field=models.CharField(default='1234', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='zip',
            field=models.CharField(default='', max_length=100, verbose_name='Zip Code'),
            preserve_default=False,
        ),
    ]
