# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0005_auto_20170805_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='address_line_1',
            field=models.CharField(help_text='First line of address', max_length=100),
        ),
        migrations.AlterField(
            model_name='chef',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Second line of address', max_length=100),
        ),
        migrations.AlterField(
            model_name='chef',
            name='bank_account_number',
            field=models.CharField(help_text='Value should come from Stripe.js call in the client.', max_length=4, verbose_name='Last 4 digits of account number'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='bank_account_status',
            field=models.CharField(help_text='Value should come from Stripe.js call in the client.', max_length=30, verbose_name='Stripe Bank Account Status'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='bank_name',
            field=models.CharField(help_text='Value should come from Stripe.js call in the client.', max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='bank_routing_number',
            field=models.CharField(help_text='Value should come from Stripe.js call in the client.', max_length=50, verbose_name='Bank Rounting Number'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='dob',
            field=models.DateField(help_text='Date of birth in format: yyyy-mm-dd. For example: 1994-07-13', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='legal_entity_type',
            field=models.CharField(choices=[('individual', 'individual'), ('company', 'company')], default='individual', help_text="'individual' is the default", max_length=10),
        ),
        migrations.AlterField(
            model_name='chef',
            name='ssn_last_4',
            field=models.CharField(help_text='Last 4 digits of Social Security Number', max_length=4),
        ),
        migrations.AlterField(
            model_name='chef',
            name='zip',
            field=models.CharField(help_text='Zip or Postal Code', max_length=100, verbose_name='Zip Code'),
        ),
    ]
