///////////////////////// ACTION TYPES ////////////////////////////
export const TOKEN_SET = 'TOKEN_SET'
export const TOKEN_UNSET = 'TOKEN_UNSET'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'

export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING'
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS'
export const SIGNUP_REQUEST_ERROR = 'SIGNUP_REQUEST_ERROR'
export const RESET_SIGNUP_FORM = 'RESET_SIGNUP_FORM'

export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR'
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM'
export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST'

export const MEAL_REQUEST = 'MEAL_REQUEST'
export const MEAL_REQUEST_SUCCESS = 'MEAL_REQUEST_SUCCESS'
export const MEAL_REQUEST_ERROR = 'MEAL_REQUEST_ERROR'

export const MEALS_REQUESTING = 'MEALS_REQUESTING'
export const MEALS_REQUEST_SUCCESS = 'MEALS_REQUEST_SUCCESS'
export const MEALS_REQUEST_ERROR = 'MEALS_REQUEST_ERROR'
export const INVALIDATE_MEAL_LIST = 'INVALIDATE_MEAL_LIST'

export const NEW_MEAL_REQUESTING = 'NEW_MEAL_REQUESTING'
export const NEW_MEAL_REQUEST_SUCCESS = 'NEW_MEAL_REQUEST_SUCCESS'
export const NEW_MEAL_REQUEST_ERROR = 'NEW_MEAL_REQUEST_ERROR'
export const RESET_NEW_MEAL_FORM = 'RESET_NEW_MEAL_FORM'

export const DELETE_MEAL_REQUEST = 'DELETE_MEAL_REQUEST'
export const DELETE_MEAL_REQUEST_SUCCESS = 'DELETE_MEAL_REQUEST_SUCCESS'
export const DELETE_MEAL_REQUEST_ERROR = 'DELETE_MEAL_REQUEST_ERROR'

export const EDIT_MEAL_REQUEST = 'EDIT_MEAL_REQUEST'
export const EDIT_MEAL_REQUEST_SUCCESS = 'EDIT_MEAL_REQUEST_SUCCESS'
export const EDIT_MEAL_REQUEST_ERROR = 'EDIT_MEAL_REQUEST_ERROR'


export const RSVP_REQUESTING = 'RSVP_REQUESTING'
export const RSVP_REQUEST_SUCCESS = 'RSVP_REQUEST_SUCCESS'
export const RSVP_REQUEST_ERROR = 'RSVP_REQUEST_ERROR'
export const RSVP_NEXT_BUTTON_CLICKED = 'RSVP_NEXT_BUTTON_CLICKED'
export const RSVP_BACK_BUTTON_CLICKED = 'RSVP_BACK_BUTTON_CLICKED'
export const RSVP_CARD_VALIDITY_CHANGED = 'RSVP_CARD_VALIDITY_CHANGED'

export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_REQUEST_SUCCESS = 'PROFILE_REQUEST_SUCCESS'
export const PROFILE_REQUEST_ERROR = 'PROFILE_REQUEST_ERROR'

export const CLIENT_PROFILE_REQUEST = 'CLIENT_PROFILE_REQUEST'
export const CLIENT_PROFILE_REQUEST_SUCCESS = 'CLIENT_PROFILE_REQUEST_SUCCESS'
export const CLIENT_PROFILE_REQUEST_ERROR = 'CLIENT_PROFILE_REQUEST_ERROR'

export const INIT_EDIT_PROFILE_FORM = 'INIT_EDIT_PROFILE_FORM'
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const EDIT_PROFILE_REQUEST_SUCCESS = 'EDIT_PROFILE_REQUEST_SUCCESS'
export const EDIT_PROFILE_REQUEST_ERROR = 'EDIT_PROFILE_REQUEST_ERROR'
export const RESET_EDIT_PROFILE_FORM = 'RESET_EDIT_PROFILE_FORM'

export const CHEF_APPLY_REQUEST = 'CHEF_APPLY_REQUEST'
export const CHEF_APPLY_REQUEST_SUCCESS = 'CHEF_APPLY_REQUEST_SUCCESS'
export const CHEF_APPLY_REQUEST_ERROR = 'CHEF_APPLY_REQUEST_ERROR'
export const RESET_CHEF_APPLICATION_FORM = 'RESET_CHEF_APPLICATION_FORM'

export const STRIPE_CUSTOMER_TOKEN_REQUEST = 'STRIPE_CUSTOMER_TOKEN_REQUEST'
export const STRIPE_CUSTOMER_TOKEN_REQUEST_SUCCESS = 'STRIPE_CUSTOMER_TOKEN_REQUEST_SUCCESS'
export const STRIPE_CUSTOMER_TOKEN_REQUEST_ERROR = 'STRIPE_CUSTOMER_TOKEN_REQUEST_ERROR'



export const CUSTOMER_REQUEST = 'CUSTOMER_REQUEST'
export const CUSTOMER_REQUEST_SUCCESS = 'CUSTOMER_REQUEST_SUCCESS'
export const CUSTOMER_REQUEST_ERROR = 'CUSTOMER_REQUEST_ERROR'
export const CUSTOMER_CREATE_REQUEST = 'CUSTOMER_CREATE_REQUEST'
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS'
export const CUSTOMER_CREATE_ERROR = 'CUSTOMER_CREATE_ERROR'
export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST'
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS'
export const CUSTOMER_UPDATE_ERROR = 'CUSTOMER_UPDATE_ERROR'

export const FACEBOOK_CONNECTED = 'FACEBOOK_CONNECTED'


// Actions from REact Redux Form
export const RRF_RESET = 'rrf/reset'

export const DELIVERY_OPTIONS = [
  { key: 1, text: 'Delivery', value: 'delivery' },
  { key: 2, text: 'Dine-In', value: 'dine_in' },
  { key: 3, text: 'Pickup', value: 'pickup'},
]

// Form models
export const EDIT_MEAL_FORM = "forms.editMeal"
export const EDIT_PROFILE_FORM = "forms.editProfile"
export const LOGIN_FORM = "forms.login"
export const NEW_MEAL_FORM = "forms.newMeal"
export const RSVP_FORM = "forms.rsvp"
export const SIGNUP_FORM = "forms.signup"
export const CHEF_APPLICATION_FORM = "forms.chefApplication"
// need to find consistent way of naming actions
