# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(max_length=100, verbose_name='Stripe Customer Id')),
                ('billing_card_number', models.CharField(max_length=4, verbose_name='Stripe Card Last 4 Digits')),
                ('billing_address_1', models.CharField(blank=True, max_length=100, verbose_name='Stripe Card Address Line 1')),
                ('billing_address_2', models.CharField(blank=True, max_length=100, verbose_name='Stripe Card Address Line 2')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Stripe Card City')),
                ('billing_state', models.CharField(blank=True, max_length=100, verbose_name='Stripe Card State')),
                ('billing_zip', models.CharField(max_length=100, verbose_name='Stripe Card Zip')),
                ('billing_country', models.CharField(max_length=100, verbose_name='Stripe Card Country')),
                ('billing_type', models.CharField(max_length=100, verbose_name='Stripe Card Type')),
                ('billing_expiry_month', models.SmallIntegerField(verbose_name='Stripe Card Expiry Month')),
                ('billing_expiry_year', models.SmallIntegerField(verbose_name='Stripe Card Expiry Year')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
