# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_state',
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_address_1',
            field=models.CharField(blank=True, help_text='Value can come from Stripe.js call if customer has entered it during account creation.', max_length=100, verbose_name='Billing Address Line 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_address_2',
            field=models.CharField(blank=True, help_text='Value can come from Stripe.js call if customer has entered it during account creation.', max_length=100, verbose_name='Billing Address Line 2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_card_number',
            field=models.CharField(help_text='Value should come from Stripe.js call in the client.', max_length=4, verbose_name='Last 4 Digits of Card Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(blank=True, help_text='Value can come from Stripe.js call if customer has entered it during account creation.', max_length=100, verbose_name='Billing City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_country',
            field=models.CharField(help_text='Value should come from Stripe.js call in the client.', max_length=100, verbose_name='Billing Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_expiry_month',
            field=models.SmallIntegerField(help_text='Two digit exiry month. Value should come from Stripe.js call in the client.', verbose_name='Card Expiry Month'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_expiry_year',
            field=models.SmallIntegerField(help_text='Two digit exiry year. Value should come from Stripe.js call in the client.', verbose_name='Card Expiry Year'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_type',
            field=models.CharField(help_text='Visa, American Express, MasterCard, Discover, JCB, Diners Club, or Unknown. Value should come from Stripe.js call in the client.', max_length=100, verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_zip',
            field=models.CharField(help_text='Value should come from Stripe.js call in the client.', max_length=100, verbose_name='Billing Zip Code'),
        ),
    ]
