# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charge_id', models.CharField(max_length=40, verbose_name='Stripe Charge Id')),
                ('transfer_group', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transfer_id', models.CharField(max_length=40, verbose_name='Stripe Transfer Id')),
                ('transfer_group', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField(default=1)),
                ('delivery_method', models.CharField(default='', max_length=100)),
                ('comments', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_purchased', to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='meals.Meal')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.AddField(
            model_name='payout',
            name='rsvp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='rsvps.Rsvp'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rsvp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rsvps.Rsvp'),
        ),
    ]
