# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transfer_group',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='transfer_group',
        ),
    ]
