# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-05 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvps', '0002_auto_20170804_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payout',
            new_name='Transfer',
        ),
    ]
