# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvps', '0005_transfer_payout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Default is False'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='servings',
            field=models.IntegerField(default=1, help_text='Default is 1'),
        ),
    ]
