# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(default='')),
                ('image', models.ImageField(blank=True, upload_to=profiles.models.Profile.profile_directory_path)),
                ('school', models.CharField(default='', max_length=255)),
                ('work', models.CharField(default='', max_length=255)),
                ('chef', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
